added fragments, navigations and buttons with transitions
TalosFN/FinancialPortfolioApp pull request #1
Opened 2024-07-08 09:18 UTC by TalosFN

Fragments, navigation, buttons

2024-07-08 13:44 UTC, arkadi4 approved these changes

2024-07-08 14:27 UTC, pzinkevich42innowise requested changes

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/build.gradle
> +    }
Зачем?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/SettingsFragment.kt
Что это за файл?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +    }
Мы навигируемся другим способом, зачем это?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/home/HomeFragment.kt
> +            findNavController().navigate(R.id.action_homeFragment_to_portfolio_list_fragment)
Добавить saveArgs и использовать Directions

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +    </fragment>
Constraint состоит из одного фрагмента? В чём его роль тут?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset_list.xml
> +        app:layout_constraintStart_toStartOf="parent" />
Может тулбар лучше подключить?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +    tools:context=".presentation.home.HomeFragment">
В чём преимущество использования тега layout вместо тега вьюшки?

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/partfolio/PartfolioListFragment.kt
> +class PartfolioListFragment : Fragment() {
```suggestion
class PortfolioListFragment : Fragment() {
```

2024-07-08 14:27 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_settings.xml
> +    <RelativeLayout
Constraint?

2024-07-10 04:01 UTC, pzinkevich42innowise requested changes

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/build.gradle
> +    def nav_version = "2.7.7"
зачем?

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +
лишняя пустая строчка

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +
строчка

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/home/HomeFragment.kt
> +// HomeFragment.kt
а без этого можно как-то узнать какой файл сейчас открыт?

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsFragment.kt
> +    private var _binding: FragmentSettingsBinding? = null
На примере этого фрагмента:

Если в переменную что-то записать, то это что-то в ней будет лежать, пока не перезапишется. В твоём случае мы складываем в переменную объект binding, через который доступны вьюшки, контекст и куча всего ещё и перезаписываем только на повторном входе (который может и не произойти). ЖЦ этого объекта меньше, чем у фрагмента. Поэтому нам бы хотелось, чтобы после завершения ЖЦ вьюшки, эта переменная почистилась и не висела мёртвым грузом в памяти до следующего перезахода.

Это называется утечка памяти, и её необходимо решить

2024-07-10 04:01 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_asset_list.xml
> +        app:layout_constraintTop_toTopOf="parent"
А Constraint тут зачем?

2024-07-10 14:51 UTC, pzinkevich42innowise approved these changes

2024-07-10 22:03 UTC, merged