Feature/portfolio list
TalosFN/FinancialPortfolioApp pull request #10
Opened 2024-08-01 08:40 UTC by arkadi4

Можно ли таким образом делать ресайклер с разными вью?
Можно ли расширять сущности доменной модели на данной стадии проекта?

2024-08-01 08:51 UTC, TalosFN approved these changes

2024-08-01 14:39 UTC, Valentin2508247 requested changes

2024-08-01 14:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/rv/PortfolioListDiffCallBack.kt
> +        return oldItem.name == newItem.name
некорректная реализация

2024-08-01 14:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/rv/BasePortfolioListViewHolder.kt
> +            itemPortfolioName.text = "Cash: ${item.name}"
все строки из ресурсов

2024-08-01 14:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/rv/PortfolioListAdapter.kt
> +    var onClick: (PortfolioItem) -> Unit = { }
private val и в конструктор

2024-08-02 12:37 UTC, Valentin2508247 requested changes

2024-08-02 12:37 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +import com.example.financialportfolioapp.presentation.portfoliolist.rv.TypeFactory
domain не должен зависеть от presentation

2024-08-02 12:37 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
В нашем случае не страшно менять presentation модели для целей UI слоя, но лучше так не делать. 
Решением было бы сделать отдельные модели для презентейшен слоя, и в них положить getType и getHolder, чтобы не писать фабрику

2024-08-06 14:54 UTC, Valentin2508247 requested changes
сделай переход на корутины отдельным пр-ом

2024-08-06 14:54 UTC, Valentin2508247 commented on app/src/main/res/values/strings.xml
> +    <string name="future_price">Future price:</string>
сделай string с параметрами
Future price: %1$s
аналогично и для схожих строк

2024-08-06 14:54 UTC, Valentin2508247 commented on app/src/main/res/layout/item_bond_portfolio_list.xml
> +                    android:text="@string/future_price"/>
сделай один TextView вместо LinearLayout + 2 x TextView
используй string ресурсы с параметрами
аналогично и для других аналогичных view

2024-08-06 14:54 UTC, Valentin2508247 commented on app/src/main/res/layout/item_cash_portfolio_list.xml
> +            <LinearLayout
аналогично

2024-08-06 14:54 UTC, Valentin2508247 commented on app/src/main/res/layout/item_stock_portfolio_list.xml
> +            <LinearLayout
аналогично

2024-08-06 14:54 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/rv/PortfolioListDiffCallBack.kt
> +    @SuppressLint("DiffUtilEquals")
нужна ли аннотация @SuppressLint("DiffUtilEquals")

2024-08-07 13:16 UTC, Valentin2508247 approved these changes

2024-08-07 16:24 UTC, merged