added async calls
TalosFN/FinancialPortfolioApp pull request #11
Opened 2024-08-08 09:12 UTC by arkadi4

2024-08-08 18:41 UTC, TalosFN approved these changes

2024-08-09 08:33 UTC, Valentin2508247 requested changes

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch { assetDetailViewModel.loadItem(assetId) }
верни назад

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsViewModel.kt
> +    suspend fun loadItem(assetId: Int) {
сделай не suspend и запускай корутину через viewModelScope

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +            viewLifecycleOwner.lifecycleScope.launch { assetListViewModel.deleteItem(asset) }
аналогично

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListViewModel.kt
> +        viewModelScope.launch {
просто loadData()

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListViewModel.kt
> +    private suspend fun loadData() {
не suspend и запуск корутины через viewModelScope

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
> +    suspend fun setDefaultCurrency(newCurrency: String) {
не suspend, запуск корутины через viewModelScope

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/stringselector/SelectCurrencyDialogFragment.kt
> +            viewLifecycleOwner.lifecycleScope.launch {
settingsScreenViewModel.setDefaultCurrency(currenciesList[position].currencyName)

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/PortfolioListViewModel.kt
> +        viewModelScope.launch { _items.value = mapDataToUiModel(loadSampleData()) }
сделай маппинг не на UI потоке

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/PortfolioListViewModel.kt
> +        viewModelScope.launch { _items.value = mapDataToUiModel(loadSampleData()) }
по умолчанию у viewModelScope идет Dispatcher.Main.immediate, то есть код будет работать на main потоке

2024-08-09 08:33 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/portfoliolist/PortfolioListViewModel.kt
> +    private suspend fun loadSampleData(): List<PortfolioItemInterface> {
не suspend, запуск корутины через viewModelScope

2024-08-09 11:22 UTC, Valentin2508247 approved these changes

2024-08-09 12:42 UTC, merged