Changed SharedPreferences to DataStore
TalosFN/FinancialPortfolioApp pull request #12
Opened 2024-08-15 11:41 UTC by arkadi4

2024-08-15 12:39 UTC, TalosFN approved these changes

2024-08-15 13:00 UTC, Valentin2508247 requested changes

2024-08-15 13:00 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/data/repository/SettingsStorageRepositoryImpl.kt
> +    @ApplicationContext private val context: Context
давай передавать DataStore<Preferences> как зависимость в конструктор через DI вместо контекста

2024-08-16 08:09 UTC, Valentin2508247 approved these changes

2024-08-16 08:49 UTC, merged