created database with few related tables + dao interfaces
TalosFN/FinancialPortfolioApp pull request #14
Opened 2024-08-15 13:25 UTC by TalosFN

datdbase, tables, dao interfaces (wil be upgraded in the future), addet to repository

2024-08-15 13:28 UTC, arkadi4 approved these changes

2024-08-16 08:13 UTC, Valentin2508247 requested changes

2024-08-16 08:13 UTC, Valentin2508247 commented on app/build.gradle
> +    kapt "androidx.room:room-compiler:2.6.1"
через version catalog

2024-08-16 08:13 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> +roomRuntime = "2.6.1"
можешь использовать общую версию

2024-08-16 18:31 UTC, pzinkevich42innowise requested changes

2024-08-16 18:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/data/entities/AssetEntity.kt
> +
строчка

2024-08-16 18:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/data/entities/BondEntity.kt
> +
строчка

2024-08-16 18:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/data/entities/CashEntity.kt
> +
строчка

2024-08-16 18:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/data/entities/StockEntity.kt
> +
строчка

2024-08-16 18:31 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/data/local/AssetDao.kt
> +    @Insert(onConflict = OnConflictStrategy.REPLACE)
upsert

2024-08-16 20:31 UTC, pzinkevich42innowise approved these changes

2024-08-16 20:51 UTC, merged