deleted unused tables, added data transfer from database to presentat…
TalosFN/FinancialPortfolioApp pull request #16
Opened 2024-08-17 20:58 UTC by TalosFN

Поменял структуру базы данных, сделал передачу данных в presentation-слой, изменил репозитории для корректной работы, извините за большой пул реквест, большая задача

2024-08-17 21:08 UTC, arkadi4 approved these changes

2024-08-18 18:19 UTC, pzinkevich42innowise requested changes

2024-08-18 18:19 UTC, pzinkevich42innowise commented on app/build.gradle
> +    id "org.jetbrains.kotlin.plugin.serialization" version "1.9.0"
Все подключения через version catalog

2024-08-18 18:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    //    mutableMapOf(dateOfLastPriceUpdate to getPriceString())
Неиспользуемый код надо удалять, а не комментировать

2024-08-18 18:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +                        }
Давай как-нибудь придумаем метод один для одинаковых действий

2024-08-18 18:19 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsViewModel.kt
> +    val item: LiveData<Any?> get() = _item
Может есть другой общий наследник?

2024-08-18 21:08 UTC, pzinkevich42innowise requested changes

2024-08-18 21:08 UTC, pzinkevich42innowise commented on app/build.gradle
>      id 'kotlin-kapt'
А тут не надо менять?

2024-08-18 21:08 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +                        }
Тут без изменений? Типа пофиг?

2024-08-18 21:53 UTC, TalosFN commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +                        }
Изменения есть, каждый метод теперь отображает особенные для каждого актива параметры и скрывает ненужные

2024-08-19 15:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +                        }
ну вот я вижу такой метод примерно:
fun populateScreen(
nameValue: String,
amountValue: String,
...
dividendsValue: String? = null, // если null - visibility = gone, иначе значение
...
И так по всем полям. Как будто можно один метод написать и его 3 раза переиспользовать

2024-08-19 15:48 UTC, pzinkevich42innowise requested changes
Надо доработать наполнение экрана

2024-08-20 15:51 UTC, pzinkevich42innowise approved these changes

2024-08-20 15:52 UTC, merged