Feature/api call
TalosFN/FinancialPortfolioApp pull request #17
Opened 2024-08-18 20:30 UTC by arkadi4

2024-08-18 20:31 UTC, TalosFN approved these changes

2024-08-18 21:10 UTC, pzinkevich42innowise requested changes

2024-08-18 21:10 UTC, pzinkevich42innowise commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization'
тут и выше через version catalog

2024-08-18 21:10 UTC, pzinkevich42innowise commented on build.gradle
> +    id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.10' apply false
version catalog

2024-08-18 21:10 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
Зайти в либу и посмотреть, что она устаревшая, репозиторий в архиве, и что надо использовать что-то другое не надо? Большими буквами на третьей строке же всё написано...

<img width="728" alt="image" src="https://github.com/user-attachments/assets/d0884cd6-f414-4844-bfd9-4a11c50056cf">

2024-08-19 15:58 UTC, pzinkevich42innowise approved these changes
поправь версии, и вливай

2024-08-19 15:58 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +serialization = "1.9.0"
2.0.10 ?

2024-08-19 15:58 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +kotlinxSerializationJson = "1.6.0"
1.7.1 ?

2024-08-20 07:54 UTC, merged