Feature/create
TalosFN/FinancialPortfolioApp pull request #18
Opened 2024-08-20 17:39 UTC by TalosFN

Creation of assets with the addition to Asset List

2024-08-20 19:36 UTC, arkadi4 approved these changes

2024-08-21 14:57 UTC, Valentin2508247 requested changes

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createBond/CreateBondFragment.kt
> +            val name = binding.editName.text.toString()
лучше выносить в метод

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createBond/CreateBondViewModel.kt
> +@HiltViewModel
забыл пустую строку после imports

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createBond/CreateBondViewModel.kt
> +):ViewModel() {
проверь форматирование в файле

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createCash/CreateCashFragment.kt
> +class CreateCashFragment : Fragment() {
нет строки после imports и лишняя после объявления

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createCash/CreateCashViewModel.kt
проверь форматирование

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createStock/CreateStockFragment.kt
форматирование

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createStock/CreateStockFragment.kt
> +        binding.btnSaveStock.setOnClickListener {
вынеси в метод

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createCash/CreateCashFragment.kt
> +        binding.btnSave.setOnClickListener {
вынеси метод

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createStock/CreateStockViewModel.kt
форматирование

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_create_bond.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем нужен FrameLayout?

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_create_cash.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем нужен FrameLayout?

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_create_stock.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем нужен FrameLayout?

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_home.xml
> +    <Button
везде есть отступы между view, тут нет

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_select_asset_type.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
зачем нужен FrameLayout?

2024-08-21 14:57 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_select_asset_type.xml
атрибуты view написаны в разном порядке
легче читать, если соблюдается одинаковый порядок
на Windows можно воспользоваться CTR + ALT + L для автоформатирования

2024-08-21 14:57 UTC, Valentin2508247 commented on gradle/libs.versions.toml
> -kotlinxSerializationJson = "1.7.1"
почему версию понизил?

2024-08-21 15:43 UTC, TalosFN commented on gradle/libs.versions.toml
> -kotlinxSerializationJson = "1.7.1"
> почему версию понизил?

эта версия serialization не работает с версией kotlin 1.9.0

2024-08-22 10:25 UTC, Valentin2508247 reviewed
очень много неправильного форматирования
нет какого-то единого стиля
много ненужных пустых строк
в некоторых файлах нет пустой строки в конце, в некоторых сразу несколько строк

2024-08-22 10:25 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createBond/CreateBondFragment.kt
> +        fun saveBond() {
сделай private функцию во фрагменте

2024-08-22 10:25 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createBond/CreateBondFragment.kt
> +
ненужная строка

2024-08-22 10:25 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createCash/CreateCashFragment.kt
> +
почему 2 строки?

2024-08-22 10:25 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/createStock/CreateStockFragment.kt
> +    fun saveStock() {
провер строки

2024-08-22 12:06 UTC, Valentin2508247 approved these changes

2024-08-22 14:20 UTC, merged