Feature/domain models
TalosFN/FinancialPortfolioApp pull request #3
Opened 2024-07-09 10:47 UTC by arkadi4

Файл DataSample временно находится в Data

2024-07-09 14:06 UTC, TalosFN approved these changes

2024-07-09 18:55 UTC, pzinkevich42innowise requested changes

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +    var date: Date
Дата чего?

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +    var price: Double
Цена и дата не являются прямыми свойствами актива. Мы вполне можем полностью использовать актив, никак не взаимодействуя с его ценой и датой этой цены, если речь, конечно, не идёт о номинальной стоимости и дате эмиссии (а эти параметры нам особо и не нужны в приложении). Так, например, мы можем оперировать 5 акциями ОАО "Вася Пупкин и Ко", вполне без цены и даты выставления этой цены.

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +    var price: Double
price: Double - тут и далее Double чего? Какими единицами измерения характеризуется цена?

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +interface PortfolioCashInterface {
1. Как-то надо переназвать эти интерфейсы, не очень понятно их назначение из названия
2. Может это абстрактный класс?

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    var amount: Int
Спорно, но требования по возможности разделения активов не было, так что тут ок, но хотелось бы иметь единый интерфейс

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +data class InterestBearingBond(
Не очень удачное название

2024-07-09 18:55 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +data class Share(
Наверное, Stock звучит лучше, но в принципе понятно

2024-07-10 20:14 UTC, pzinkevich42innowise reviewed
Есть вопросики

2024-07-10 20:14 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +data class Asset(
А зачем этот дата класс?

2024-07-10 20:14 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    var priceHistory: MutableMap<Calendar, Double>
Не слишком ли тяжёлый объект получится? Для отображения списка придётся практически всю базу доставать и набивать инфой объекты, которая и не факт что понадобится

2024-07-10 21:11 UTC, arkadi4 commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +data class Asset(
Для отображения в списке AssetList экземпляров этого класса, что-то вроде списка активов, интересующих пользователя, кликнув на которые, пользователь направляется на AssetDetails экран, где по id или имени может получить дополнительную информацию (для валют сделать запрос на API и посмотреть курс этой валюты, для ценных ценных бумаг посмотреть из базы данных предыдущую стоимость, если он её уже вводил ранее).

2024-07-10 21:13 UTC, arkadi4 commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +data class Asset(
Если я правильно понял техническое задание

2024-07-15 07:28 UTC, AlexVLive requested changes

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/data/DataSample.kt
> +    var assetList: MutableList<AssetInterface> = mutableListOf(
Нет необходимости использовать var

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/data/DataSample.kt
> +    var portfolioItemsList: MutableList<PortfolioItemInterface> = mutableListOf(
Аналогично (var -> val)

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    var priceString: String = "$priceValue ${priceCurrency.currencyName}"
Лучше сделать это fun() чем переменной var

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    var history: MutableMap<Calendar, String> = mutableMapOf(dateOfLastPriceUpdate to priceString)
var -> val

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    val someExchangeTradedFundProperty: Any
Вместо Any лучше использовать конрентный тип

2024-07-15 07:28 UTC, AlexVLive commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/PortfolioItem.kt
> +    val someIndexedBondProperty: Any
Аналогично: any -> конкретный тип

2024-07-15 07:28 UTC, AlexVLive commented on app/src/test/java/com/example/financialportfolioapp/ExampleUnitTest.kt
Example бы удалить

2024-07-15 07:28 UTC, AlexVLive commented on code_style/InnowiseGroup.xml
Файлы xml принято именовать с маленькой буквы

2024-07-16 19:29 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financialportfolioapp/domain/entities/Asset.kt
> +data class Asset(
Зачем тогда нужен AssetInterface?

2024-07-16 19:39 UTC, pzinkevich42innowise commented
Предлагаю убрать AssetInterface и сделать просто модели

2024-07-22 15:35 UTC, merged