String selector for settings screen
TalosFN/FinancialPortfolioApp pull request #5
Opened 2024-07-17 11:28 UTC by arkadi4

String selector for currencies on settings screen and store default currency in SharedPreferences

2024-07-18 09:53 UTC, TalosFN approved these changes

2024-07-19 08:40 UTC, Valentin2508247 requested changes

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsFragment.kt
> +            val modalDialogFragment = SelectCurrencyDialogFragment()
не обязательно создавать локальную переменную

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
> +    val uiState: MutableLiveData<SettingsState> get() = _uiState
val uiState: LiveData<SettingsState>

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
Давай сделаем отдельную класс, который будет обращаться в preferences
И вызывать из вьюмодели методы класса

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
> +        sharedPrefs.edit()?.putString("default Currency", newCurrency)?.apply()
вынести ключ в константу, например в companion object

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
> +        _uiState.postValue(_uiState.value!!.copy(defaultCurrencyValue = newCurrency))
postValue не нужен
_uiState.value = ...

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/stringselector/SelectCurrencyDialogFragment.kt
> +
нужно занулить binding в onDestoyView()

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/settings/SettingsScreenViewmodel.kt
> +class SettingsScreenViewmodel(application: Application) : AndroidViewModel(application) {
давай сделаем обычную ViewModel вместо AndroidViewModel
зависимости (для работы с Preference) можно передать в конструктор

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/stringselector/SelectCurrencyDialogFragment.kt
> +        dialog?.setOnShowListener { it ->
override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
        return BottomSheetDialog(requireContext(), theme).apply {
            behavior.state = BottomSheetBehavior.STATE_EXPANDED
        }
    }

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_bottomsheet.xml
> +    android:id="@+id/bottom_sheet"
почему у списка id называется bottom_sheet?

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/stringselector/SelectCurrencyDialogFragment.kt
> +        val adapter = ArrayAdapter(
логику настройки view в onViewCreated

2024-07-19 08:40 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/stringselector/SelectCurrencyDialogFragment.kt
> +        binding.bottomSheet.adapter = adapter
непонятный нейминг id у binding.bottomSheet

2024-07-24 10:01 UTC, Valentin2508247 approved these changes

2024-07-24 10:01 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/home/HomeFragment.kt
> +
зачем строка?

2024-07-24 11:46 UTC, merged