detail fragment, data binding, repository + impl
TalosFN/FinancialPortfolioApp pull request #8
Opened 2024-07-24 11:21 UTC by TalosFN

created detail fragment, filed with data, created portfolio item repository + impl

2024-07-24 11:39 UTC, Valentin2508247 requested changes

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/data/AssetRepositoryImpl.kt
> +        return getAssets().first { it.id == assetId }
getAssetById(assetId: Int): Asset? и getAssets().firstOrNull
могут быть краши, если элемент с id не будет найден

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/data/PortfolioItemRepositoryImpl.kt
> +        return getItems().first { it.id == assetId }
PortfolioItemInterface? и firstOrNull

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsViewModel.kt
> +    fun loadItem(assetId: Int): LiveData<PortfolioItemInterface> {
давай без возвращения livedata из метода

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +            val calendar = item.price.dateOfLastPriceUpdate
давай сделаем отдельный класс-утилиту для работы с датой/временем
туда можно сложить и переиспользовать форматтеры ("dd-MM-yyyy HH:mm:ss")
а также добавить методы для форматирования

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +            binding.nameValue.text = item.name
можно binding.apply

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListViewModel.kt
> +
так более читаемо
private val _assets = MutableLiveData<List<Asset>>()
val assets: LiveData<List<Asset>> get() = _assets

private val _items = MutableLiveData<List<PortfolioItemInterface>>()
val items: LiveData<List<PortfolioItemInterface>> get() = _items

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +            if (!assetListViewModel.assetExists(assetId)) {
скорее всего проверка не нужна будет, если сделать результат getAssetById() nullable

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListViewModel.kt
> +    fun assetExists(assetId: Int): Boolean {
форматирование

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_details.xml
все android:text через ресурсы

2024-07-24 11:39 UTC, Valentin2508247 commented on app/src/main/res/layout/fragment_asset_details.xml
проверьте отступы и форматирование

2024-07-25 09:27 UTC, Valentin2508247 requested changes
не все обязательные комменты исправлены или добавлен коммент/ответ
мерж конфликты
нет аппрува от второго участника

2024-07-25 09:27 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetDetails/AssetDetailsFragment.kt
> +
сделай return если пришел null:
assetDetailViewModel.item.observe(viewLifecycleOwner) {
    val item = it ?: return

2024-07-25 10:24 UTC, arkadi4 approved these changes

2024-07-25 12:00 UTC, Valentin2508247 requested changes

2024-07-25 12:00 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/utils/DateTimeUtils.kt
> +    fun getCurrentDateTime(): LocalDateTime {
поле currentDateTime инициализизуется единожды при первом обращении к object DateTimeUtils
функция getCurrentDateTime() будет работать некорректно

2024-07-25 12:00 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/utils/DateTimeUtils.kt
> +    fun formatDateTime(dateTime: LocalDateTime): String {
более гибко будет  fun formatDateTime(dateTime: LocalDateTime, dateTimeFormatter: DateTimeFormatter  = dateTimeFormatter )

2024-07-25 13:17 UTC, Valentin2508247 approved these changes

2024-07-25 13:18 UTC, merged