interactor, delete buttons
TalosFN/FinancialPortfolioApp pull request #9
Opened 2024-07-28 20:10 UTC by TalosFN

Added interactor with delete method, delete buttons for assets

2024-07-28 20:15 UTC, arkadi4 approved these changes

2024-07-29 08:27 UTC, Valentin2508247 requested changes

2024-07-29 08:27 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/domain/interactor/Interactor.kt
> +class Interactor(
слишком общий нейминг класса
нужно поменять на что-то более конкретное

2024-07-29 08:27 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/presentation/assetList/AssetListFragment.kt
> +            assetListViewModel.deleteItem(asset)
не нужна переменная
assetListViewModel.deleteItem(asset.id)

2024-07-29 08:27 UTC, Valentin2508247 commented on app/src/main/java/com/example/financialportfolioapp/domain/interactor/Interactor.kt
> +class Interactor(
@ Inject constructor

2024-07-29 13:26 UTC, Valentin2508247 approved these changes

2024-07-29 13:48 UTC, merged